package tabletopfx.gamelogic.component

/**
 * ### Architectural Role: Abstract Spatial Domain Identifier
 * Defines the restricted type boundary for structural coordination states inside the logic layer.
 * This contract enforces layout-agnostic values that prevent the core game loop from tracking
 * visual coordinates or layout screen pixels.
 *
 * @see AbsoluteLoc
 * @see SquareGridLoc
 * @see HexGridLoc
 * @see IndexedLoc
 * @see UnknownLoc
 */
sealed interface Location

/**
 * Continuous physical layout coordinate system.
 * Typically utilized for miniatures, open-field war games, or free-form token canvas fields.
 *
 * @property x Continuous positioning offset relative to the absolute map tracking origin.
 * @property y Continuous positioning offset relative to the absolute map tracking origin.
 */
data class AbsoluteLoc(val x: Double, val y: Double) : Location

/**
 * Discrete 2D orthogonal grid coordinate cell identifier.
 * Primarily maps chessboard structures, checkers matrix planes, or square tactical layouts.
 *
 * @property row Zero-indexed row coordinate representing the target grid row.
 * @property col Zero-indexed column coordinate representing the target grid column.
 */
data class SquareGridLoc(val row: Int, val col: Int) : Location

/**
 * Discrete 2D hexagonal grid coordinate layout key.
 * Tailored explicitly for map tracking fields using classic hex geometries.
 *
 * @property row Zero-indexed row marker on the targeted hexagonal layout grid.
 * @property col Zero-indexed column marker on the targeted hexagonal layout grid.
 */
data class HexGridLoc(val row: Int, val col: Int) : Location

/**
 * Structured sequence-based logical placement container index.
 * Maps sequential game regions where items occupy a strict structural ordering index.
 *
 * | Example Implementation | Context Application |
 * | :--- | :--- |
 * | Hand Zones | Tracking cards held in an active player space. |
 * | Draw Decks | Storing ordered game draw cards sequentially. |
 * | Discard Piles | Maintaining dead cards stacked in order of elimination. |
 *
 * @property zoneName Distinct tag identifying the targeted relative region workspace.
 * @property index Order index position representing placement precedence inside the deck list container.
 */
data class IndexedLoc(val zoneName: String, val index: Int = 0) : Location

/**
 * Universal error boundary fallback token.
 * Generated by the view layer coordinate translators when pixel inputs collapse completely out of
 * active board bounds or fall into unmapped screen margins.
 */
data object UnknownLoc : Location